"""
EXODIA schemas.py — Compatibility shim.

타입 정의의 Source of Truth는 models/outputs.py와 models/inputs.py이다.
이 파일은 레거시 코드(layers/*, pipeline.py, tests/)의 import 경로를
깨지 않기 위한 re-export 전용이다.

⚠️ 이 파일에 class 정의를 추가하지 마라.
"""
from exodia.models.inputs import (
    ClientMessageSignals,
    ClientSignals,
    ConversationSession,
    RawTurn,
    TurnMetadata,
)
from exodia.models.outputs import (
    BiasShift,
    ContributingMetric,
    ConsistencyEvidence,
    ConsistencyOutput,
    CrossValidationEvidence,
    DirectionMetrics,
    EngineError,
    FrictionSource,
    GapAnalysis,
    GapComponents,
    IntegrityEvidence,
    IntegrityOutput,
    IntensityAxis,
    L0NormOutput,
    L1Output,
    L2Metrics,
    L2Output,
    L3Output,
    L4Output,
    L5Output,
    L7Output,
    LSMFeatures,
    MatchResult,
    MentionFlags,
    MentionSummary,
    MorphologyOutput,
    NLPAggregate,
    PipelineMetadata,
    PragmaticsOutput,
    Profile,
    RiskAssessment,
    RiskFlag,
    RiskReport,
    SessionProfile,
    SpanHint,
    StructuralAxis,
    StyleShift,
    SurfaceFeatures,
    SyntaxOutput,
    TimeseriesData,
    TransitionData,
    TransitionQC,
    UserProfile,
)
from exodia.calibration import CalibrationConfig, Phase
from exodia.adapter.base import CompatibilityLabel, RiskAction
from exodia.adapter.default import DefaultAdapter

# ── 레거시 alias (layers/*, pipeline.py에서 사용) ──
L0Output = L0NormOutput  # v2 이름 → v3 canonical
ClientSignalMessage = ClientMessageSignals  # 레거시 이름

__all__ = [
    "BiasShift",
    "CalibrationConfig",
    "ClientMessageSignals",
    "ClientSignalMessage",
    "ClientSignals",
    "CompatibilityLabel",
    "ConversationSession",
    "RawTurn",
    "TurnMetadata",
    "ContributingMetric",
    "ConsistencyEvidence",
    "ConsistencyOutput",
    "CrossValidationEvidence",
    "DefaultAdapter",
    "DirectionMetrics",
    "EngineError",
    "FrictionSource",
    "GapAnalysis",
    "GapComponents",
    "IntegrityEvidence",
    "IntegrityOutput",
    "IntensityAxis",
    "L0NormOutput",
    "L0Output",
    "L1Output",
    "L2Metrics",
    "L2Output",
    "L3Output",
    "L4Output",
    "L5Output",
    "L7Output",
    "LSMFeatures",
    "MatchResult",
    "MentionFlags",
    "MentionSummary",
    "MorphologyOutput",
    "NLPAggregate",
    "Phase",
    "PipelineMetadata",
    "PragmaticsOutput",
    "Profile",
    "RiskAction",
    "RiskAssessment",
    "RiskFlag",
    "RiskReport",
    "SessionProfile",
    "SpanHint",
    "StructuralAxis",
    "StyleShift",
    "SurfaceFeatures",
    "SyntaxOutput",
    "TimeseriesData",
    "TransitionData",
    "TransitionQC",
    "UserProfile",
]
